name: Build Qt5 Windows Executable (MinGW)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw81'
          cache: true

      - name: Configure and Build (MinGW)
        working-directory: ${{ github.workspace }}  # Run from the root directory
        run: |
          mkdir build
          cd build
          qmake ../Weatherapp.pro -r -spec win32-g++ CONFIG+=release  # Use correct path
          dir  # Verify Makefile exists
          mingw32-make  # Only use mingw32-make

      - name: Deploy Qt Dependencies
        working-directory: ${{ github.workspace }}/build
        run: |
          windeployqt WeatherApp.exe  # Ensure the correct executable name is used

      - name: Package Executable
        working-directory: ${{ github.workspace }}/build
        run: |
          mkdir release
          mv WeatherApp.exe release/  # Moving the executable
          mv *.dll release/  # Moving necessary DLLs
          tar -czvf release.tar.gz release/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Qt5-Windows-Executable
          path: build/release/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          files: build/release.tar.gz
          tag_name: v1.0.${{ github.run_number }}
          name: "Release v1.0.${{ github.run_number }}"
          body: "Automatically generated release."
          draft: false
          prerelease: false
