name: Build Qt Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up MinGW
      - name: Set up MinGW
        uses: msys2/setup-msys2-action@v2
        with:
          update: true

      # Install Qt and MinGW dependencies
      - name: Install Qt and MinGW dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm mingw-w64-x86_64-qt5 mingw-w64-x86_64-gcc

      # Set up the environment for Qt and MinGW
      - name: Add MinGW to PATH
        run: echo "C:\\msys64\\mingw64\\bin" >> $GITHUB_PATH

      # Build the Qt project
      - name: Build the Qt project
        run: |
          cd ${{ github.workspace }}
          qmake Weatherapp.pro -spec win32-g++
          mingw32-make

      # Upload the built executable
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: Weatherapp.exe
          path: Weatherapp.exe
