name: Build Qt Application

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Qt 5.12
        uses: jurplel/install-qt-action@v2
        with:
          qt-version: '5.12.12'  # Specify the Qt version here
          qt-archive: 'qt5'      # Specify the Qt archive name

      - name: Install Dependencies
        run: |
          choco install mingw --version=8.1.0  # Install MinGW for building

      - name: Build Application
        run: |
          qmake Weatherapp.pro CONFIG+=release
          mingw32-make

      - name: Package Application
        run: |
          mkdir output
          cp -r Weatherapp.exe output/
          cp -r *.dll output/  # Copy all DLLs in the current directory
          # Add any other necessary files

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: WeatherApp
          path: output/
