name: Build Qt5 Windows Executable (MinGW)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'  # Adjust to your Qt version
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw81'
          cache: true

      - name: Configure and Build (MinGW)
        run: |
          mkdir build
          cd build
          qmake Wheatherapp.pro  # Adjust to your actual .pro file
          mingw32-make

      - name: Deploy Qt Dependencies
        run: |
          cd build
          windeployqt Wheatherapp.exe  # Replace with actual exe name

      - name: Package Executable
        run: |
          mkdir release
          mv build/your_project.exe release/
          mv build/*.dll release/
          tar -czvf release.tar.gz release/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Qt5-Windows-Executable
          path: release/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          files: release.tar.gz
          tag_name: v1.0.${{ github.run_number }}
          name: "Release v1.0.${{ github.run_number }}"
          body: "Automatically generated release."
          draft: false
          prerelease: false
