name: C++ Qt Naming Convention Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  naming-convention-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run naming convention check
        run: |
          echo "Checking C++ naming conventions..."
          python3 - <<'EOF'
          import os
          import re

          # Define regex patterns and replacements
          patterns = {
              "Member Variable": (r"\b(m)([A-Z][a-zA-Z0-9_]*)", r"m\2"),
              "Parameter": (r"\b(p)([A-Z][a-zA-Z0-9_]*)", r"p\2"),
              "Local Variable": (r"\b(l)([A-Z][a-zA-Z0-9_]*)", r"l\2"),
              "Constant": (r"\b(K)([A-Z][a-zA-Z0-9_]*)", r"K\2"),
              "Static Variable": (r"\b(s)([A-Z][a-zA-Z0-9_]*)", r"s\2"),
              "Class Name": (r"\b([A-Z][a-zA-Z0-9_]*)\s*{", r"\1 {"),
              "Function Name": (r"\b([a-z][a-zA-Z0-9_]*)\s*\(", r"\1("),
          }

          errors = []

          # Walk through the repository and check C++ files
          for root, _, files in os.walk("."):
              for file in files:
                  if (file.endswith(".cpp") or file.endswith(".h")) and file != "main.cpp":
                      file_path = os.path.join(root, file)
                      with open(file_path, "r", encoding="utf-8") as f:
                          lines = f.readlines()
                      
                      new_lines = []
                      for i, line in enumerate(lines, start=1):
                          modified = line
                          for category, (pattern, replacement) in patterns.items():
                              modified = re.sub(pattern, replacement, modified)
                          new_lines.append(modified)
                          if line != modified:
                              errors.append(f"{file}:{i}: Naming violation in {category}, auto-fixed.")
                      
                      with open(file_path, "w", encoding="utf-8") as f:
                          f.writelines(new_lines)

          # Output results
          if errors:
              print("Naming convention violations found and fixed:")
              for error in errors:
                  print(error)
          else:
              print("All naming conventions passed!")
          EOF
